---
Standards:
  -
    Title: Sample Lesson
    Description: Sample Lesson
    UID: 118215c501bf9df5966730f4870af0ca
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 7ee8b71deb4347b15da65897c7b7d77a
        Path: /01-sample-lesson/lesson.checkpoint.md
