version: "3.8"
services:
  db:
    build: ./database/
    env_file:
      - 'variables.env'
    healthcheck:
      test: exit 0
    expose: 
      - "5432"
  testenv :
    build: .
    command: python -m pytest
    depends_on:
      db: 
        condition: service_healthy
    env_file:
      - 'variables.env'
    links:
      - db

